### ISSUE TITLE
Notification icons for ios7 to ios10 are missing

### ISSUE THREAD

**Issue by GabLeRoux** [leopic/makeAppIcon#3]
Everything in issue title ;)
When generating icons using this nice little peace of command line, notification icons are not being generated.

I suppose it shouldn't be hard to fix.

**Comment by leopic** [comment]
Hi @GabLeRoux 

It's just a matter of adding the sizes and their respective multipliers into the sizes object around here https://github.com/leopic/makeAppIcon/blob/master/lib/index.js#L52.

I'll get to this on Friday, sorry I created this module way before iOS10 came around so there are probably quite a few things that need to be updated.

**Comment by leopic** [comment]
@GabLeRoux release v1.2.0 addresses this issue, feel free to reach out if you need something else

Cheers,
Leo
