### ISSUE TITLE
Error in terminal

### ISSUE THREAD

**Issue by joeyyellow2005** [leopic/makeAppIcon#5]
when I try to do:
```
brew uninstall imagemagick graphicsmagick libpng jpeg
brew cleanup -s
brew install graphicsmagick
```
it just says:

> -bash: brew: command not found

sooooo, not quite sure what to do here.

**Comment by leopic** [comment]
Hi there, could I get some more information about this issue?

Is this somehow related to https://github.com/leopic/makeAppIcon/issues/2 ?

**Comment by joeyyellow2005** [comment]
No, it just says 

> -bash: brew: command not found

when I try do do the code on the requirements page. If I try to do the code in the usage page it does that too. I want to use this, but I guess it may not work. Help would be much appreciated!

**Comment by leopic** [comment]
Do you have https://brew.sh/ installed?

**Comment by joeyyellow2005** [comment]
Thanks! that should fix it.

**Comment by leopic** [comment]
I'll make sure to add it to the README file, thank you for filing a ticket!
